# Use Node 24
FROM node:24-alpine

# Set working directory
WORKDIR /app

# Copy package.json and lock first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the code
COPY . .

# Build TypeScript
RUN npm run build

# Expose port
EXPOSE 3000

# Run the app
CMD ["node", "dist/main.js"]
